server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: GATEWAY
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: USERS-API
        uri: http://localhost:8081/
        predicates:
          - Path=/users/**
      - id: PRODUCTS-API
        uri: http://localhost:8082/
        predicates:
          - Path=/products/**
      - id: PAYMENT-API
        uri: http://localhost:8083/
        predicates:
          - Path=/payment/**
      - id: ORDERS-API
        uri: http://localhost:8084/
        predicates:
          - Path=/orders/**
